export const portofolios = [
  {
    image: "/asset/artapuri.png",
    title: "PT Artapuri Digital Mediatama",
    desk: "company profile",
    link: "#",
    category: "client",
  },

  {
    image: "/asset/bcolebak.png",
    title: "Portal Berita BCO Lebak",
    desk: "portal berita",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/portalines.png",
    title: "Portal Berita Portalines",
    desk: "portal berita",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/chemweek.png",
    title: "Chemistry Week",
    desk: "company profile",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/ncc.png",
    title: "National Chemistry Challenge",
    desk: "website lomba chemistry",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/oasisteknik.png",
    title: "PT Oasisteknik",
    desk: "company profile",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/ssa.png",
    title: "PT Sinar Samudra Abadi",
    desk: "company profile",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/tanzglobal.png",
    title: "PT Tanz Global",
    desk: "company profile",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/pesonavanila.png",
    title: "PT Pesona Vanila",
    desk: "company profile",
    link: "#",
    category: "client",
  },
  {
    image: "/asset/wedding.png",
    title: "Undangan Pernikahan",
    desk: "Invitation",
    link: "https://sasa.runbyindonesia.com/",
    category: "client",
  },
  {
    image: "/asset/genfrugal.png",
    title: "Financial Planner Management",
    desk: "Company Profile",
    link: "https://genfrugal.my.id/",
    category: "client",
  },
  {
    image: "/asset/atria.png",
    title: "Atria Store",
    desk: "E Commerce",
    link: "https://atria.co.id/",
    category: "client",
  },
  {
    image: "/asset/bookshelf.png",
    title: "Booksehlf Apps",
    desk: "Web Apps",
    link: "https://bookshelf-apps-pi.vercel.app/",
    category: "personal",
  },
  {
    image: "/asset/movie.png",
    title: "Movie List",
    desk: "Web Apps",
    link: "https://my-movie-sigma-khaki.vercel.app/",
    category: "personal",
  },
  {
    image: "/asset/notes.png",
    title: "Notes Apps",
    desk: "Web Apps",
    link: "https://notes-apps-sooty.vercel.app/",
    category: "personal",
  },
  {
    image: "/asset/undanginkuy.png",
    title: "Undangin Kuy",
    desk: "Landing Page",
    link: "https://undanginkuy.com/",
    category: "client",
  },
];
